In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data\iris.csv")

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df.shape

(150, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [6]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [9]:
df.column= pd.DataFrame(df[['sepal_length', 'sepal_width', 'petal_length','species', 'petal_width',]])

C:\Users\urban\AppData\Local\Temp/ipykernel_1992/2794532237.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.column= pd.DataFrame(df[['sepal_length', 'sepal_width', 'petal_length','species', 'petal_width',]])

In [10]:
df.column

     sepal_length  sepal_width  petal_length         species  petal_width
0             5.1          3.5           1.4     Iris-setosa          0.2
1             4.9          3.0           1.4     Iris-setosa          0.2
2             4.7          3.2           1.3     Iris-setosa          0.2
3             4.6          3.1           1.5     Iris-setosa          0.2
4             5.0          3.6           1.4     Iris-setosa          0.2
..            ...          ...           ...             ...          ...
145           6.7          3.0           5.2  Iris-virginica          2.3
146           6.3          2.5           5.0  Iris-virginica          1.9
147           6.5          3.0           5.2  Iris-virginica          2.0
148           6.2          3.4           5.4  Iris-virginica          2.3
149           5.9          3.0           5.1  Iris-virginica          1.8

[150 rows x 5 columns]

In [12]:
 import json

  
# Opening JSON file
f = open('data/algoparams_from_ui.json')
  
# returns JSON object as 
# a dictionary
data = json.load(f)

In [13]:
data

{'session_name': 'test',
 'session_description': 'test',
 'design_state_data': {'session_info': {'project_id': '1',
   'experiment_id': 'kkkk-11',
   'dataset': 'iris_modified.csv',
   'session_name': 'test',
   'session_description': 'test'},
  'target': {'prediction_type': 'Regression',
   'target': 'petal_width',
   'type': 'regression',
   'partitioning': True},
  'train': {'policy': 'Split the dataset',
   'time_variable': 'sepal_length',
   'sampling_method': 'No sampling(whole data)',
   'split': 'Randomly',
   'k_fold': False,
   'train_ratio': 0,
   'random_seed': 0},
  'metrics': {'optomize_model_hyperparameters_for': 'AUC',
   'optimize_threshold_for': 'F1 Score',
   'compute_lift_at': 0,
   'cost_matrix_gain_for_true_prediction_true_result': 1,
   'cost_matrix_gain_for_true_prediction_false_result': 0,
   'cost_matrix_gain_for_false_prediction_true_result': 0,
   'cost_matrix_gain_for_false_prediction_false_result': 0},
  'feature_handling': {'sepal_length': {'feature_name': 'sepal_length',
    'is_selected': True,
    'feature_variable_type': 'numerical',
    'feature_details': {'numerical_handling': 'Keep as regular numerical feature',
     'rescaling': 'No rescaling',
     'make_derived_feats': False,
     'missing_values': 'Impute',
     'impute_with': 'Average of values',
     'impute_value': 0}},
   'sepal_width': {'feature_name': 'sepal_width',
    'is_selected': True,
    'feature_variable_type': 'numerical',
    'feature_details': {'numerical_handling': 'Keep as regular numerical feature',
     'rescaling': 'No rescaling',
     'make_derived_feats': False,
     'missing_values': 'Impute',
     'impute_with': 'custom',
     'impute_value': -1}},
   'petal_length': {'feature_name': 'petal_length',
    'is_selected': True,
    'feature_variable_type': 'numerical',
    'feature_details': {'numerical_handling': 'Keep as regular numerical feature',
     'rescaling': 'No rescaling',
     'make_derived_feats': False,
     'missing_values': 'Impute',
     'impute_with': 'Average of values',
     'impute_value': 0}},
   'petal_width': {'feature_name': 'petal_width',
    'is_selected': True,
    'feature_variable_type': 'numerical',
    'feature_details': {'numerical_handling': 'Keep as regular numerical feature',
     'rescaling': 'No rescaling',
     'make_derived_feats': False,
     'missing_values': 'Impute',
     'impute_with': 'custom',
     'impute_value': -2}},
   'species': {'feature_name': 'species',
    'is_selected': True,
    'feature_variable_type': 'text',
    'feature_details': {'text_handling': 'Tokenize and hash',
     'hash_columns': 0}}},
  'feature_generation': {'linear_interactions': [['petal_length',
     'sepal_width']],
   'linear_scalar_type': 'robust',
   'polynomial_interactions': ['petal_length/sepal_width',
    'petal_width/species'],
   'explicit_pairwise_interactions': ['sepal_width/sepal_length',
    'petal_width/sepal_length']},
  'feature_reduction': {'feature_reduction_method': 'Tree-based',
   'num_of_features_to_keep': '4',
   'num_of_trees': '5',
   'depth_of_trees': '6'},
  'hyperparameters': {'stratergy': 'Grid Search',
   'shuffle_grid': True,
   'random_state': 1,
   'max_iterations': 2,
   'max_search_time': 3,
   'parallelism': 5,
   'cross_validation_stratergy': 'Time-based K-fold(with overlap)',
   'num_of_folds': 6,
   'split_ratio': 0,
   'stratified': True},
  'weighting_stratergy': {'weighting_stratergy_method': 'Sample weights',
   'weighting_stratergy_weight_variable': 'petal_length'},
  'probability_calibration': {'probability_calibration_method': 'Sigmoid - Platt Scaling'},
  'algorithms': {'RandomForestClassifier': {'model_name': 'Random Forest Classifier',
    'is_selected': False,
    'min_trees': 10,
    'max_trees': 30,
    'feature_sampling_statergy': 'Default',
    'min_depth': 20,
    'max_depth': 30,
    'min_samples_per_leaf_min_value': 5,
    'min_samples_per_leaf_max_value': 50,
    'parallelism': 0},
   'RandomForestRegressor': {'model_name': 'Random Forest Regressor',
    'is_selected': True,
    'min_trees': 10,
    'max_trees': 20,
    'feature_sampling_statergy': 'Default',
    'min_depth': 20,
    'max_depth': 25,
    'min_samples_per_leaf_min_value': 5,
    'min_samples_per_leaf_max_value': 10,
    'parallelism': 0},
   'GBTClassifier': {'model_name': 'Gradient Boosted Trees',
    'is_selected': False,
    'num_of_BoostingStages': [67, 89],
    'feature_sampling_statergy': 'Fixed number',
    'learningRate': [],
    'use_deviance': True,
    'use_exponential': False,
    'fixed_number': 22,
    'min_subsample': 1,
    'max_subsample': 2,
    'min_stepsize': 0.1,
    'max_stepsize': 0.5,
    'min_iter': 20,
    'max_iter': 40,
    'min_depth': 5,
    'max_depth': 7},
   'GBTRegressor': {'model_name': 'Gradient Boosted Trees',
    'is_selected': False,
    'num_of_BoostingStages': [67, 89],
    'feature_sampling_statergy': 'Fixed number',
    'use_deviance': True,
    'use_exponential': False,
    'fixed_number': 22,
    'min_subsample': 1,
    'max_subsample': 2,
    'min_stepsize': 0.1,
    'max_stepsize': 0.5,
    'min_iter': 20,
    'max_iter': 40,
    'min_depth': 5,
    'max_depth': 7},
   'LinearRegression': {'model_name': 'LinearRegression',
    'is_selected': False,
    'parallelism': 2,
    'min_iter': 30,
    'max_iter': 50,
    'min_regparam': 0.5,
    'max_regparam': 0.8,
    'min_elasticnet': 0.5,
    'max_elasticnet': 0.8},
   'LogisticRegression': {'model_name': 'LogisticRegression',
    'is_selected': False,
    'parallelism': 2,
    'min_iter': 30,
    'max_iter': 50,
    'min_regparam': 0.5,
    'max_regparam': 0.8,
    'min_elasticnet': 0.5,
    'max_elasticnet': 0.8},
   'RidgeRegression': {'model_name': 'RidgeRegression',
    'is_selected': False,
    'regularization_term': 'Specify values to test',
    'min_iter': 30,
    'max_iter': 50,
    'min_regparam': 0.5,
    'max_regparam': 0.8},
   'LassoRegression': {'model_name': 'Lasso Regression',
    'is_selected': False,
    'regularization_term': 'Specify values to test',
    'min_iter': 30,
    'max_iter': 50,
    'min_regparam': 0.5,
    'max_regparam': 0.8},
   'ElasticNetRegression': {'model_name': 'Lasso Regression',
    'is_selected': False,
    'regularization_term': 'Specify values to test',
    'min_iter': 30,
    'max_iter': 50,
    'min_regparam': 0.5,
    'max_regparam': 0.8,
    'min_elasticnet': 0.5,
    'max_elasticnet': 0.8},
   'xg_boost': {'model_name': 'XG Boost',
    'is_selected': False,
    'use_gradient_boosted_tree': True,
    'dart': True,
    'tree_method': '',
    'random_state': 0,
    'max_num_of_trees': 0,
    'early_stopping': True,
    'early_stopping_rounds': 2,
    'max_depth_of_tree': [56, 89],
    'learningRate': [89, 76],
    'l1_regularization': [77],
    'l2_regularization': [78],
    'gamma': [68],
    'min_child_weight': [67],
    'sub_sample': [67],
    'col_sample_by_tree': [67],
    'replace_missing_values': False,
    'parallelism': 0},
   'DecisionTreeRegressor': {'model_name': 'Decision Tree',
    'is_selected': False,
    'min_depth': 4,
    'max_depth': 7,
    'use_gini': False,
    'use_entropy': True,
    'min_samples_per_leaf': [12, 6],
    'use_best': True,
    'use_random': True},
   'DecisionTreeClassifier': {'model_name': 'Decision Tree',
    'is_selected': False,
    'min_depth': 4,
    'max_depth': 7,
    'use_gini': False,
    'use_entropy': True,
    'min_samples_per_leaf': [12, 6],
    'use_best': True,
    'use_random': True},
   'SVM': {'model_name': 'Support Vector Machine',
    'is_selected': False,
    'linear_kernel': True,
    'rep_kernel': True,
    'polynomial_kernel': True,
    'sigmoid_kernel': True,
    'c_value': [566, 79],
    'auto': True,
    'scale': True,
    'custom_gamma_values': True,
    'tolerance': 7,
    'max_iterations': 7},
   'SGD': {'model_name': 'Stochastic Gradient Descent',
    'is_selected': False,
    'use_logistics': True,
    'use_modified_hubber_loss': False,
    'max_iterations': False,
    'tolerance': 56,
    'use_l1_regularization': 'on',
    'use_l2_regularization': 'on',
    'use_elastic_net_regularization': True,
    'alpha_value': [79, 56],
    'parallelism': 1},
   'KNN': {'model_name': 'KNN',
    'is_selected': False,
    'k_value': [78],
    'distance_weighting': True,
    'neighbour_finding_algorithm': 'Automatic',
    'random_state': 0,
    'p_value': 0},
   'extra_random_trees': {'model_name': 'Extra Random Trees',
    'is_selected': False,
    'num_of_trees': [45, 489],
    'feature_sampling_statergy': 'Square root and Logarithm',
    'max_depth': [12, 45],
    'min_samples_per_leaf': [78, 56],
    'parallelism': 3},
   'neural_network': {'model_name': 'Neural Network',
    'is_selected': False,
    'hidden_layer_sizes': [67, 89],
    'activation': '',
    'alpha_value': 0,
    'max_iterations': 0,
    'convergence_tolerance': 0,
    'early_stopping': True,
    'solver': 'ADAM',
    'shuffle_data': True,
    'initial_learning_rate': 0,
    'automatic_batching': True,
    'beta_1': 0,
    'beta_2': 0,
    'epsilon': 0,
    'power_t': 0,
    'momentum': 0,
    'use_nesterov_momentum': False}}}}

In [15]:
for keys in data.keys():
    print(keys)

session_name
session_description
design_state_data

In [16]:
for values in data.values():
   print(values)

test
test
{'session_info': {'project_id': '1', 'experiment_id': 'kkkk-11', 'dataset': 'iris_modified.csv', 'session_name': 'test', 'session_description': 'test'}, 'target': {'prediction_type': 'Regression', 'target': 'petal_width', 'type': 'regression', 'partitioning': True}, 'train': {'policy': 'Split the dataset', 'time_variable': 'sepal_length', 'sampling_method': 'No sampling(whole data)', 'split': 'Randomly', 'k_fold': False, 'train_ratio': 0, 'random_seed': 0}, 'metrics': {'optomize_model_hyperparameters_for': 'AUC', 'optimize_threshold_for': 'F1 Score', 'compute_lift_at': 0, 'cost_matrix_gain_for_true_prediction_true_result': 1, 'cost_matrix_gain_for_true_prediction_false_result': 0, 'cost_matrix_gain_for_false_prediction_true_result': 0, 'cost_matrix_gain_for_false_prediction_false_result': 0}, 'feature_handling': {'sepal_length': {'feature_name': 'sepal_length', 'is_selected': True, 'feature_variable_type': 'numerical', 'feature_details': {'numerical_handling': 'Keep as regular numerical feature', 'rescaling': 'No rescaling', 'make_derived_feats': False, 'missing_values': 'Impute', 'impute_with': 'Average of values', 'impute_value': 0}}, 'sepal_width': {'feature_name': 'sepal_width', 'is_selected': True, 'feature_variable_type': 'numerical', 'feature_details': {'numerical_handling': 'Keep as regular numerical feature', 'rescaling': 'No rescaling', 'make_derived_feats': False, 'missing_values': 'Impute', 'impute_with': 'custom', 'impute_value': -1}}, 'petal_length': {'feature_name': 'petal_length', 'is_selected': True, 'feature_variable_type': 'numerical', 'feature_details': {'numerical_handling': 'Keep as regular numerical feature', 'rescaling': 'No rescaling', 'make_derived_feats': False, 'missing_values': 'Impute', 'impute_with': 'Average of values', 'impute_value': 0}}, 'petal_width': {'feature_name': 'petal_width', 'is_selected': True, 'feature_variable_type': 'numerical', 'feature_details': {'numerical_handling': 'Keep as regular numerical feature', 'rescaling': 'No rescaling', 'make_derived_feats': False, 'missing_values': 'Impute', 'impute_with': 'custom', 'impute_value': -2}}, 'species': {'feature_name': 'species', 'is_selected': True, 'feature_variable_type': 'text', 'feature_details': {'text_handling': 'Tokenize and hash', 'hash_columns': 0}}}, 'feature_generation': {'linear_interactions': [['petal_length', 'sepal_width']], 'linear_scalar_type': 'robust', 'polynomial_interactions': ['petal_length/sepal_width', 'petal_width/species'], 'explicit_pairwise_interactions': ['sepal_width/sepal_length', 'petal_width/sepal_length']}, 'feature_reduction': {'feature_reduction_method': 'Tree-based', 'num_of_features_to_keep': '4', 'num_of_trees': '5', 'depth_of_trees': '6'}, 'hyperparameters': {'stratergy': 'Grid Search', 'shuffle_grid': True, 'random_state': 1, 'max_iterations': 2, 'max_search_time': 3, 'parallelism': 5, 'cross_validation_stratergy': 'Time-based K-fold(with overlap)', 'num_of_folds': 6, 'split_ratio': 0, 'stratified': True}, 'weighting_stratergy': {'weighting_stratergy_method': 'Sample weights', 'weighting_stratergy_weight_variable': 'petal_length'}, 'probability_calibration': {'probability_calibration_method': 'Sigmoid - Platt Scaling'}, 'algorithms': {'RandomForestClassifier': {'model_name': 'Random Forest Classifier', 'is_selected': False, 'min_trees': 10, 'max_trees': 30, 'feature_sampling_statergy': 'Default', 'min_depth': 20, 'max_depth': 30, 'min_samples_per_leaf_min_value': 5, 'min_samples_per_leaf_max_value': 50, 'parallelism': 0}, 'RandomForestRegressor': {'model_name': 'Random Forest Regressor', 'is_selected': True, 'min_trees': 10, 'max_trees': 20, 'feature_sampling_statergy': 'Default', 'min_depth': 20, 'max_depth': 25, 'min_samples_per_leaf_min_value': 5, 'min_samples_per_leaf_max_value': 10, 'parallelism': 0}, 'GBTClassifier': {'model_name': 'Gradient Boosted Trees', 'is_selected': False, 'num_of_BoostingStages': [67, 89], 'feature_sampling_statergy': 'Fixed number', 'learningRate': [], 'use_deviance': True, 'use_exponential': False, 'fixed_number': 22, 'min_subsample': 1, 'max_subsample': 2, 'min_stepsize': 0.1, 'max_stepsize': 0.5, 'min_iter': 20, 'max_iter': 40, 'min_depth': 5, 'max_depth': 7}, 'GBTRegressor': {'model_name': 'Gradient Boosted Trees', 'is_selected': False, 'num_of_BoostingStages': [67, 89], 'feature_sampling_statergy': 'Fixed number', 'use_deviance': True, 'use_exponential': False, 'fixed_number': 22, 'min_subsample': 1, 'max_subsample': 2, 'min_stepsize': 0.1, 'max_stepsize': 0.5, 'min_iter': 20, 'max_iter': 40, 'min_depth': 5, 'max_depth': 7}, 'LinearRegression': {'model_name': 'LinearRegression', 'is_selected': False, 'parallelism': 2, 'min_iter': 30, 'max_iter': 50, 'min_regparam': 0.5, 'max_regparam': 0.8, 'min_elasticnet': 0.5, 'max_elasticnet': 0.8}, 'LogisticRegression': {'model_name': 'LogisticRegression', 'is_selected': False, 'parallelism': 2, 'min_iter': 30, 'max_iter': 50, 'min_regparam': 0.5, 'max_regparam': 0.8, 'min_elasticnet': 0.5, 'max_elasticnet': 0.8}, 'RidgeRegression': {'model_name': 'RidgeRegression', 'is_selected': False, 'regularization_term': 'Specify values to test', 'min_iter': 30, 'max_iter': 50, 'min_regparam': 0.5, 'max_regparam': 0.8}, 'LassoRegression': {'model_name': 'Lasso Regression', 'is_selected': False, 'regularization_term': 'Specify values to test', 'min_iter': 30, 'max_iter': 50, 'min_regparam': 0.5, 'max_regparam': 0.8}, 'ElasticNetRegression': {'model_name': 'Lasso Regression', 'is_selected': False, 'regularization_term': 'Specify values to test', 'min_iter': 30, 'max_iter': 50, 'min_regparam': 0.5, 'max_regparam': 0.8, 'min_elasticnet': 0.5, 'max_elasticnet': 0.8}, 'xg_boost': {'model_name': 'XG Boost', 'is_selected': False, 'use_gradient_boosted_tree': True, 'dart': True, 'tree_method': '', 'random_state': 0, 'max_num_of_trees': 0, 'early_stopping': True, 'early_stopping_rounds': 2, 'max_depth_of_tree': [56, 89], 'learningRate': [89, 76], 'l1_regularization': [77], 'l2_regularization': [78], 'gamma': [68], 'min_child_weight': [67], 'sub_sample': [67], 'col_sample_by_tree': [67], 'replace_missing_values': False, 'parallelism': 0}, 'DecisionTreeRegressor': {'model_name': 'Decision Tree', 'is_selected': False, 'min_depth': 4, 'max_depth': 7, 'use_gini': False, 'use_entropy': True, 'min_samples_per_leaf': [12, 6], 'use_best': True, 'use_random': True}, 'DecisionTreeClassifier': {'model_name': 'Decision Tree', 'is_selected': False, 'min_depth': 4, 'max_depth': 7, 'use_gini': False, 'use_entropy': True, 'min_samples_per_leaf': [12, 6], 'use_best': True, 'use_random': True}, 'SVM': {'model_name': 'Support Vector Machine', 'is_selected': False, 'linear_kernel': True, 'rep_kernel': True, 'polynomial_kernel': True, 'sigmoid_kernel': True, 'c_value': [566, 79], 'auto': True, 'scale': True, 'custom_gamma_values': True, 'tolerance': 7, 'max_iterations': 7}, 'SGD': {'model_name': 'Stochastic Gradient Descent', 'is_selected': False, 'use_logistics': True, 'use_modified_hubber_loss': False, 'max_iterations': False, 'tolerance': 56, 'use_l1_regularization': 'on', 'use_l2_regularization': 'on', 'use_elastic_net_regularization': True, 'alpha_value': [79, 56], 'parallelism': 1}, 'KNN': {'model_name': 'KNN', 'is_selected': False, 'k_value': [78], 'distance_weighting': True, 'neighbour_finding_algorithm': 'Automatic', 'random_state': 0, 'p_value': 0}, 'extra_random_trees': {'model_name': 'Extra Random Trees', 'is_selected': False, 'num_of_trees': [45, 489], 'feature_sampling_statergy': 'Square root and Logarithm', 'max_depth': [12, 45], 'min_samples_per_leaf': [78, 56], 'parallelism': 3}, 'neural_network': {'model_name': 'Neural Network', 'is_selected': False, 'hidden_layer_sizes': [67, 89], 'activation': '', 'alpha_value': 0, 'max_iterations': 0, 'convergence_tolerance': 0, 'early_stopping': True, 'solver': 'ADAM', 'shuffle_data': True, 'initial_learning_rate': 0, 'automatic_batching': True, 'beta_1': 0, 'beta_2': 0, 'epsilon': 0, 'power_t': 0, 'momentum': 0, 'use_nesterov_momentum': False}}}

In [17]:
X=df[["sepal_length","sepal_width","petal_length","species"]]

In [18]:
X

     sepal_length  sepal_width  petal_length         species
0             5.1          3.5           1.4     Iris-setosa
1             4.9          3.0           1.4     Iris-setosa
2             4.7          3.2           1.3     Iris-setosa
3             4.6          3.1           1.5     Iris-setosa
4             5.0          3.6           1.4     Iris-setosa
..            ...          ...           ...             ...
145           6.7          3.0           5.2  Iris-virginica
146           6.3          2.5           5.0  Iris-virginica
147           6.5          3.0           5.2  Iris-virginica
148           6.2          3.4           5.4  Iris-virginica
149           5.9          3.0           5.1  Iris-virginica

[150 rows x 4 columns]

In [19]:
Y=df[["petal_width"]]

In [20]:
Y

     petal_width
0            0.2
1            0.2
2            0.2
3            0.2
4            0.2
..           ...
145          2.3
146          1.9
147          2.0
148          2.3
149          1.8

[150 rows x 1 columns]

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
one=OneHotEncoder()

In [23]:
dummy=pd.get_dummies(df["species"])

In [24]:
dummy

     Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [25]:
df.index.name="Id"

In [26]:
df.column

     sepal_length  sepal_width  petal_length         species  petal_width
Id
0             5.1          3.5           1.4     Iris-setosa          0.2
1             4.9          3.0           1.4     Iris-setosa          0.2
2             4.7          3.2           1.3     Iris-setosa          0.2
3             4.6          3.1           1.5     Iris-setosa          0.2
4             5.0          3.6           1.4     Iris-setosa          0.2
..            ...          ...           ...             ...          ...
145           6.7          3.0           5.2  Iris-virginica          2.3
146           6.3          2.5           5.0  Iris-virginica          1.9
147           6.5          3.0           5.2  Iris-virginica          2.0
148           6.2          3.4           5.4  Iris-virginica          2.3
149           5.9          3.0           5.1  Iris-virginica          1.8

[150 rows x 5 columns]

In [27]:
df.column=pd.merge(dummy,df.column,on="Id")

In [28]:
df.column.drop("species",axis=1,inplace=True)

In [29]:
df.column

,Iris-setosa,Iris-versicolor,Iris-virginica,sepal_length,sepal_width,petal_length,petal_width
Id,,,,,,,
0,1,0,0,5.1,3.5,1.4,0.2
1,1,0,0,4.9,3.0,1.4,0.2
2,1,0,0,4.7,3.2,1.3,0.2
3,1,0,0,4.6,3.1,1.5,0.2
4,1,0,0,5.0,3.6,1.4,0.2
...,...,...,...,...,...,...,...
145,0,0,1,6.7,3.0,5.2,2.3
146,0,0,1,6.3,2.5,5.0,1.9
147,0,0,1,6.5,3.0,5.2,2.0
148,0,0,1,6.2,3.4,5.4,2.3
149,0,0,1,5.9,3.0,5.1,1.8

In [30]:
Y=df.column[["petal_width"]]

In [31]:
X=df.column[["Iris-setosa","Iris-versicolor","Iris-virginica","sepal_length","sepal_width","petal_length"]]

In [32]:
X

,Iris-setosa,Iris-versicolor,Iris-virginica,sepal_length,sepal_width,petal_length
Id,,,,,,
0,1,0,0,5.1,3.5,1.4
1,1,0,0,4.9,3.0,1.4
2,1,0,0,4.7,3.2,1.3
3,1,0,0,4.6,3.1,1.5
4,1,0,0,5.0,3.6,1.4
...,...,...,...,...,...,...
145,0,0,1,6.7,3.0,5.2
146,0,0,1,6.3,2.5,5.0
147,0,0,1,6.5,3.0,5.2
148,0,0,1,6.2,3.4,5.4
149,0,0,1,5.9,3.0,5.1

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.4, random_state=1)

In [34]:
# import module for linear regression model training 
from sklearn.linear_model import LinearRegression

In [35]:
# create an object of linearRegression class 
lr=LinearRegression()

In [36]:
# train the model using fit method pass training x and y 
lr.fit(X_train,Y_train)

LinearRegression()

In [37]:
lr.coef_ #slop

array([[-0.38223509,  0.04847848,  0.33375661, -0.14573901,  0.27800013,
         0.3498225 ]])

In [38]:
lr.intercept_

array([-0.11356879])

In [39]:
Y_pred=lr.predict(X_test)
Y_pred

array([[0.1906974 ],
       [0.93610857],
       [1.34625162],
       [0.25617524],
       [2.36411414],
       [1.57832011],
       [1.86048381],
       [0.48199042],
       [0.2685392 ],
       [2.09817732],
       [1.33862609],
       [0.39610423],
       [2.08339399],
       [1.4659817 ],
       [1.44087726],
       [0.20731415],
       [1.21171378],
       [1.52697288],
       [0.18713967],
       [0.0848885 ],
       [1.39536448],
       [1.55612068],
       [1.54157122],
       [0.20327079],
       [2.15940237],
       [1.31686995],
       [0.35998362],
       [0.34206142],
       [1.46846785],
       [1.74614489],
       [1.48908563],
       [2.06591509],
       [1.17807932],
       [2.02486452],
       [1.93739668],
       [0.28511361],
       [1.17203544],
       [0.18130522],
       [1.37519   ],
       [1.96770728],
       [1.9871867 ],
       [0.22367914],
       [1.70646655],
       [2.06723844],
       [1.38841611],
       [2.23457304],
       [0.32458252],
       [0.26605305],
       [0.12840077],
       [1.29197494],
       [0.23086137],
       [0.13040128],
       [2.49820869],
       [1.96543056],
       [2.16637518],
       [2.02486452],
       [1.77415433],
       [1.57987733],
       [2.22020856],
       [1.40745223]])

In [40]:
lr.score(X_test,Y_test)

0.9470492158667986

In [41]:
# PCA (from sklearn.decomposition import PCA)

In [42]:
from sklearn.decomposition import PCA

In [43]:
len(df.column.columns)

7

In [44]:
df.shape

(150, 5)

In [45]:
pc = PCA(n_components=6,random_state=1)

In [46]:
X = df.column.drop("petal_width",axis=1)
y = df.column["petal_width"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [47]:
X_train_pc = pc.fit_transform(X_train,y_train)
X_test_pc = pc.transform(X_test)

In [48]:
lin = LinearRegression()
lin.fit(X_train_pc,y_train)

LinearRegression()

In [49]:
lin.score(X_test_pc,y_test)

0.9451186031886996

In [50]:
from sklearn.model_selection import cross_val_score

In [51]:
lr_cross=cross_val_score(lr,X,Y,cv=5) # total 3 fold it will create

In [52]:
lr_cross

array([0.36003685, 0.92627636, 0.59314457, 0.83853395, 0.12945751])

In [53]:
import numpy as np

In [54]:
np.mean(lr_cross)

0.569489846239412